### PR TITLE
Terminology Change

### PR DESCRIPTION
**Pull request by oponder**
Towards: https://github.com/giantswarm/giantswarm/issues/3991

### CODE REVIEW

**Review by marians — APPROVED** [review]

**Comment by oponder** [comment]
@r7vme is this project still a thing? Looks like it is not setup on circle anymore.

**Comment by r7vme** [comment]
This project is not used anymore, may be archive this repo ? :thinking:

**Comment by marians** [comment]
Yes, archiving is a low-risk way to have it out of the way.

**Comment by oponder** [comment]
Ok will archive it.

**Pull request closed without merging**
